apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historyapplication
  template:
    metadata:
      labels:
        app: historyapplication
    spec:
      containers:
        - name: app
          image: "{{ .Values.DOCKER_ID }}/{{ .Values.HISTORY_APP_IMAGE_NAME }}"
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always