apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: historyapplication
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "histapp"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: historyapplication
            port:
              number: 8080
