apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historyapplication
  template:
    metadata:
      labels:
        app: historyapplication
    spec:
      containers:
        - name: app
          image: nikich/historyapplication:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: historyapplication
spec:
  selector:
    app: historyapplication
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer